### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by aiqubo** [jonas-fuchs/varVAMP#11]
$ docker pull quay.io/biocontainers/varvamp
Using default tag: latest
Error response from daemon: manifest for quay.io/biocontainers/varvamp:latest not found: manifest unknown: manifest unknown

could you tell me How fix it?

**Comment by jonas-fuchs** [comment]
Hi Aiqubo, I could reproduce the error. Thanks for pointing this out. We have no latest tag at the moment. You can resolve it by:

$ docker pull quay.io/biocontainers/varvamp:0.4--pyhdfd78af_0

I will update the documentation accordingly.

**Comment by aiqubo** [comment]
> Hi Aiqubo, I could reproduce the error. Thanks for pointing this out. We have no latest tag at the moment. You can resolve it by:
> 
> $ docker pull quay.io/biocontainers/varvamp:0.4--pyhdfd78af_0
> 
> I will update the documentation accordingly.

  Thanks
