### ISSUE TITLE
threshold for conserved nucleotides

### ISSUE THREAD

**Issue by aiqubo** [jonas-fuchs/varVAMP#12]
Can you explain it in more detail?
-t 0.89, --threshold 0.89	threshold for conserved nucleotides

Which of the following is more similar in meaning?
1) >89% nucleotides in probe and primers are conserved in all genomes;
2) or, >89% nucleotides other than primers and probes are conserved in amplicon;
3) or, >89% of all genomes maybe be  amplified

**Comment by jonas-fuchs** [comment]
Thanks for the question! Threshold means at which frequency a nucleotide at a certain position is considered a consensus nucleotide. So in reality this means, that there might be sequence mismatches up to 1-threshold in each of the primer positions. There is a bit more behind that, though. When creating the consensus sequence, varVAMP calculates the nucleotide frequency at each position and considers a nucleotide conserved if its frequency is over a threshold. When it is not, the script adds nucleotide frequencys of other nucleotides until the threshold is reached and uses those nucleotides to pick the appropriate wobble base.

Example (threshold: 0.8)

seq 1: AATAAAATTTGGG
seq 2: AAAAAAATTTGGG
seq 3: AAAAAAATTTGGG
seq 4: AATAAAATTTGGG
seq 5: AATAAAATTTGGG
seq 6: AAAAAAATTTG**A**G
seq 7: AATAAA**C**TTTGGG

con:   AAWAAAATTTGGG

Here you can see that at this threshold at position 3 an ambiguous base is used in the consensus sequence, but C and A in seq6 & 7 are not considered in the consenus sequence, which is then later used to design the primers. So in rare cases there might be a mismatch, but this can normaly be tolerated to a certain point in a PCR. This is why one has to try to increase the threshold while keeping the number of allowed ambiguous bases in the primer reasonably low. 

As I realised that this might be a bit complicated, when using the program the first time, I now implemented a automatic parameter estimation that tries to optimize the -a and/or -t parameter if none are provided. Works quite well and should be coming in the next version on pypi (hope that the next docker version will be also online soon). 

A bit of a long answer but I hope this clarifies it.

**Comment by aiqubo** [comment]
> Thanks for the question! Threshold means at which frequency a nucleotide at a certain position is considered a consensus nucleotide. So in reality this means, that there might be sequence mismatches up to 1-threshold in each of the primer positions. There is a bit more behind that, though. When creating the consensus sequence, varVAMP calculates the nucleotide frequency at each position and considers a nucleotide conserved if its frequency is over a threshold. When it is not, the script adds nucleotide frequencys of other nucleotides until the threshold is reached and uses those nucleotides to pick the appropriate wobble base.
> 
> Example (threshold: 0.8)
> 
> seq 1: AATAAAATTTGGG seq 2: AAAAAAATTTGGG seq 3: AAAAAAATTTGGG seq 4: AATAAAATTTGGG seq 5: AATAAAATTTGGG seq 6: AAAAAAATTTG**A**G seq 7: AATAAA**C**TTTGGG
> 
> con: AAWAAAATTTGGG
> 
> Here you can see that at this threshold at position 3 an ambiguous base is used in the consensus sequence, but C and A in seq6 & 7 are not considered in the consenus sequence, which is then later used to design the primers. So in rare cases there might be a mismatch, but this can normaly be tolerated to a certain point in a PCR. This is why one has to try to increase the threshold while keeping the number of allowed ambiguous bases in the primer reasonably low.
> 
> As I realised that this might be a bit complicated, when using the program the first time, I now implemented a automatic parameter estimation that tries to optimize the -a and/or -t parameter if none are provided. Works quite well and should be coming in the next version on pypi (hope that the next docker version will be also online soon).
> 
> A bit of a long answer but I hope this clarifies it.

Very clear. Thank you for your quick response
