### ISSUE TITLE
Warning about deprecated Biopython functionality

### ISSUE THREAD

**Issue by wm75** [jonas-fuchs/varVAMP#31]
With recent enough versions of Biopython varVAMP triggers the deprecation warning from:

https://github.com/biopython/biopython/blob/4fc5158970b7970907fb932eae15eb779fdea839/Bio/Application/__init__.py#L40-L49

varVAMP should do as suggested in the warning and call blast directly via stdlib subprocess.

**Comment by jonas-fuchs** [comment]
Nice fix. Thanks Wolfgang!
