### ISSUE TITLE
END_OVERLAP config setting not getting logged

### ISSUE THREAD

**Issue by wm75** [jonas-fuchs/varVAMP#35]
`config.END_OVERLAP` is a setting that does not get echoed to the log file.
I'm also wondering whether it got placed into the qPCR section of settings in the default config by accident because the code appears to use it for regular primers, too.

**Comment by jonas-fuchs** [comment]
Ok we should fix the logging in the next version. It gets used for primers and probe combination of a qpcr scheme. So placement should be correct. It it should not be used in single or tiled mode.

**Comment by jonas-fuchs** [comment]
Should now be fixed and get logged
